// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOH6bUGDsnQb42F2SYsCDjEkJh1RbXRWo',
    appId: '1:385534130608:web:fdc9bec487900d77247e75',
    messagingSenderId: '385534130608',
    projectId: 'personalfinance-tracker-app',
    authDomain: 'personalfinance-tracker-app.firebaseapp.com',
    storageBucket: 'personalfinance-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXQF81gWBI5Rlpzv6R3kIGgiO9QfOilM',
    appId: '1:385534130608:ios:d00cf14bdee99844247e75',
    messagingSenderId: '385534130608',
    projectId: 'personalfinance-tracker-app',
    storageBucket: 'personalfinance-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXQF81gWBI5Rlpzv6R3kIGgiO9QfOilM',
    appId: '1:385534130608:ios:d00cf14bdee99844247e75',
    messagingSenderId: '385534130608',
    projectId: 'personalfinance-tracker-app',
    storageBucket: 'personalfinance-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_EBbBCf6L_LMUVThfb0ZYDMN3ViY_J7I',
    appId: '1:385534130608:android:7f61aee93dcc0aa4247e75',
    messagingSenderId: '385534130608',
    projectId: 'personalfinance-tracker-app',
    storageBucket: 'personalfinance-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD3JxzK8G3w8YRCGfwkzT5Wb8wRTZMNJo',
    appId: '1:385534130608:web:cc226327381bbe31247e75',
    messagingSenderId: '385534130608',
    projectId: 'personalfinance-tracker-app',
    authDomain: 'personalfinance-tracker-app.firebaseapp.com',
    storageBucket: 'personalfinance-tracker-app.firebasestorage.app',
  );

}